twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        app_name: '%env(ES_APP_NAME)%'
        app_name_description: '%env(ES_APP_CONTENT)%'
        col_1_2: 'col-sm-12 col-md-12 col-lg-8'
        col_2_2: 'col-sm-12 col-md-12 col-lg-4'
        col_1_1: 'col-sm-12'
        row_lst: 'row row-cols-1 row-cols-md-2 row-cols-lg-3'
        col_sm_1_2: 'col-sm-12 col-md-12 col-lg-4 col-xl-3'
        col_sm_2_2: 'col-sm-12 col-md-12 col-lg-8 col-xl-9'
        news_time: '%env(ES_NEWS_TIME)%'
