twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        app_name: '%env(APPLICATION_NAME)%'
        app_name_description: '%env(APPLICATION_DESCRIPTION)%'
        col_1_2: 'col-sm-12 col-md-12 col-lg-8 col-xl-6'
        col_2_2: 'col-sm-12 col-md-12 col-lg-4'
        col_1_1: 'col-sm-12'
        row_lst: 'row row-cols-1 row-cols-md-2 row-cols-lg-3'

