# config/packages/workflow.yaml
framework:
    workflows:
        backpack_publishing:
            type: 'state_machine' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentState'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - toValidate
                - toControl
                - toCheck
                - published
                - toRevise
                - inReview
                - archived
                - toResume
                - abandonned
            transitions:
                goToValidate:
                    from: [draft, toResume]
                    to: toValidate
                goToControl:
                    from: toValidate
                    to: toControl
                goToCheck:
                    from: toControl
                    to: toCheck
                goPublished:
                    from: toCheck
                    to: published
                goToRevise:
                    from: published
                    to: toRevise
                goInReview:
                    from: toRevise
                    to: inReview
                goArchived:
                    from: [published, toRevise, inReview]
                    to: archived
                goToResume:
                    from: [toValidate, toControl, toCheck, toRevise, abandonned, archived]
                    to: toResume
                goAbandonned:
                    from: [draft, toValidate, toControl, toCheck, published, toRevise, archived, inReview, toResume]
                    to: abandonned


