# config/packages/workflow.yaml
framework:
    workflows:
        backpack_publishing:
            type: 'state_machine' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentState'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - validated
                - controled
                - resumed
                - published
                - abandonned
                - archived
            transitions:
                toValide:
                    from: draft
                    to:   validated
                toResume:
                    from: [validated, abandonned, archived]
                    to:   resumed
                toAbandonne:
                    from: [draft, resumed, validated, archived]
                    to:   abandonned
                toArchive:
                    from: [draft, published]
                    to:   archived